library nixon_app;

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:async_loader/async_loader.dart';
import 'package:audio_recorder/audio_recorder.dart';
import 'package:audioplayer/audioplayer.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/services.dart';
import 'package:http/http.dart' as http;
import 'package:intl/intl.dart';
import 'package:meta/meta.dart';
import 'package:path_provider/path_provider.dart';
import 'package:scoped_model/scoped_model.dart';

import 'models/Inspection.dart';

part 'helper/animatedPageRoute.dart';
part 'helper/authentication.dart';
part 'helper/colors.dart';
part 'helper/ensureVisibleWhenFocused.dart';
part 'helper/formHelper.dart';
part 'services/bldg_data.dart';
part 'services/inspection_Repo.dart';
part 'services/staff_data.dart';
part 'ui/components/animatedCircularProgress.dart';
part 'ui/components/audioPlayer.dart';
part 'ui/components/checkBoxFormField.dart';
part 'ui/components/dateFormField.dart';
part 'ui/components/dropDownFormField.dart';
part 'ui/components/formTextField.dart';
part 'ui/components/homepageHeader.dart';
part 'ui/components/numberFormField.dart';
part 'ui/components/nxLogo.dart';
part 'ui/components/sliderFormField.dart';
part 'ui/components/timeFormField.dart';
part 'ui/components/validator.dart';
part 'ui/inspectionForm/bldgDialog.dart';
part 'ui/inspectionForm/staffDialog.dart';
part 'ui/inspectionForm/viewCleaning.dart';
part 'ui/inspectionForm/viewInfo.dart';
part 'ui/inspectionForm/viewRecorder.dart';
part 'ui/inspectionForm/viewServices.dart';
part 'ui/inspectionForm/viewSummary.dart';
part 'ui/inspectionForm/widget.dart';
part 'ui.screen/homepage.dart';
part 'ui.screen/inspectionForm.dart';
part 'ui.screen/inspectionView.dart';
part 'ui.screen/login.dart';
part 'ui.screen/splash_page.dart';
// import 'dart:typed_data';
// import 'package:http/http.dart';
